server:
  port: 80

spring:
  application:
    name: cloud-consumer-order        #消费者订单模块,的服务名称
  cloud:
    #注册到zookeeper地址
    zookeeper:
      connect-string: 192.168.137.234:2181      #入住到zookeeper的服务中心


